[project]
name = "qs-sync-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "prefect>=3.4.6",
    "psycopg2>=2.9.10",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
]
